### ISSUE TITLE
l10n_ch_payment_slip OCRB font blurred in PIL generated slip

### ISSUE THREAD

**Issue by PCatinean** [OCA/l10n-switzerland#104]
The two modules (version 7 webkit and version 8 PIL) generate a different output even though same .ttf file is used

I have an example here showcasing the difference between the two versions:
![old_1](http://i.imgur.com/az1Nnlj.png)
![new_1](http://i.imgur.com/iI1lnXY.png)

![old_2](http://i.imgur.com/GrDQ3Du.png)
![new_2](http://i.imgur.com/xEKPWj1.png)

As you can see the PIL generated ones are considerably more blurry and also the space is considerably larger (although this can be solved by spacing via position instead of entering a blank space probably)

I tried changing DPI and font-size to no avail.

Let me know if I can provide more information

@yvaucher @nbessi

**Comment by nbessi** [comment]
@PCatinean I should add a new render using reportlab this week. 
It was in the roadmap as PIL generate heavier and blurrier PDF. The choice of the renderer will be available in the company.

Regards

Nicolas

**Comment by PCatinean** [comment]
@nbessi let me know how I can contribute I would like to speed up the process if I can

**Comment by nbessi** [comment]
@PCatinean see #105 for a fix

**Comment by PCatinean** [comment]
@nbessi thank you for the ping

I have uninstalled personal modules inheriting this, uninstalled/installed this version and then update all

It seems to be generating empty pdf's for me, maybe I'm doing something wrong

**Comment by diezcode** [comment]
same here for me, empty pdf payment_slip

**Comment by yvaucher** [comment]
@diezcode @PCatinean can you tell us which version of reportlab you are using? BTW it might be better to tell about it in PR #105

**Comment by PCatinean** [comment]
@yvaucher mine is 3.0

**Comment by nbessi** [comment]
@PCatinean is your invoice validated. 
Draft invoice should not print anything

**Comment by PCatinean** [comment]
@nbessi yes invoice is validated and has attached payment_slip objects

**Comment by nbessi** [comment]
@PCatinean I just updated to latest it seems to work fine

**Comment by diezcode** [comment]
what reportlab should be installed? 
I use the newest reportlab version

**Comment by nbessi** [comment]
Any should work form 2.4 to latest

**Comment by nbessi** [comment]
Myabe there is a problem with ubuntu reportlab. Try install using pip and virtual env.
TrueType extention must be installed

**Comment by nbessi** [comment]
I confirmed the problem comes from the reprotlab proposed with Ubuntu.

**Comment by diezcode** [comment]
In my reportlab repository I don't have an font repository. How can i add fonts there? Can you give an zip ?

**Comment by diezcode** [comment]
I have installed the newest version of reportlab but PDF is empty again. Ubuntu 14.04 python 2.7

**Comment by PCatinean** [comment]
I uninstalled OS proposed library and installed through pip and got version 3.1.44 with python 2.6.7 and I still get empty pages

**Comment by nbessi** [comment]
@PCatinean in reportlab doc they said only python 2.7 and 3  are fully supported. that also weird that you can run version 8.0 of odoo on python 2.6 as it uses dict comprehention

**Comment by PCatinean** [comment]
@nbessi My apologies it is 2.7.6 not 2.6.7, I messed up.Maybe there is something else wrong in my instance but I tried both versions of reportlab to no avail, wish I knew how to debug this further...

**Comment by nbessi** [comment]
@PCatinean @diezcode  if you run the code provided here http://stackoverflow.com/questions/23769845/why-does-reportlab-3-0-save-an-empty-pdf and it zou have an empty pdf that means that your reportlab setting is broken .   It seems that you need to install `apt-get install libfreetype6-dev` in Ubuntu to have font support required by OCRB

**Comment by nbessi** [comment]
Basically if PIL compile with all image support it should work:
http://codeinthehole.com/writing/how-to-install-pil-on-64-bit-ubuntu-1204/

**Comment by PCatinean** [comment]
@nbessi Indeed with the reportlab from the Ubuntu repository the test failed, I switched back to the pip one and the text came up in the small script even with this working, odoo restarted and l10n_ch_payment_slip upgraded it still generated two empty pages

I guess we have a mistery on our hands, feel free to join IRC if you are willing to pursue this and need faster feedback

**Comment by diezcode** [comment]
Same here
I tested it with the latest debian Package again. I installed all and imported an database dump local. The emptry pdf File still coming. 
When I try to download it like here:
![unbenannt](https://cloud.githubusercontent.com/assets/7522882/6367734/5f57197a-bcd6-11e4-8f3d-5e3c92a1358a.PNG)

I download not a pdf , I download some other file .
![unbe1nannt](https://cloud.githubusercontent.com/assets/7522882/6367708/3b373016-bcd6-11e4-8e7d-92a68be70726.PNG)

When I print the invoice as pdf, I have no problem. It's only the PDF of the payment slip that is empty.

**Comment by nbessi** [comment]
@diezcode can you attatch the PDF. I'm starting to wonder if it is not a viewer problem ?

**Comment by nbessi** [comment]
@PCatinean @diezcode If you open the PDF I generate is it blank ?
http://filebin.ca/1sr4h7cf0RFT/one_slip_per_page_from_invoice2.pdf

**Comment by diezcode** [comment]
no , I see the slip at the bottom of the pdf

this is my : http://filebin.ca/1sr7uwR0RO6t/one_slip_per_page_from_invoice3.pdf

**Comment by diezcode** [comment]
what is with this?
![unbenaaaannt](https://cloud.githubusercontent.com/assets/7522882/6368580/42117cd6-bcde-11e4-9dfa-a97ea9debb2a.PNG)

![uasdsadanbenannt](https://cloud.githubusercontent.com/assets/7522882/6368587/536e17dc-bcde-11e4-8376-5c09c5b6f9dc.PNG)

**Comment by PCatinean** [comment]
@nbessi I can see it both in the chrome pdf viewer as well as the standard ubuntu one

**Comment by diezcode** [comment]
When I test it with another Database dump that comes from another server. It shows me like this on the same server that the other pdf is empty :
http://filebin.ca/1srOqujf8NKj/one_slip_per_page_from_invoice7.pdf

**Comment by nbessi** [comment]
@diezcode I can read your pdf it is not empty

**Comment by PCatinean** [comment]
Same

**Comment by diezcode** [comment]
@nbessi  yes I know but it is not right, with white background.

**Comment by PCatinean** [comment]
@diezcode that is an option you set from your company bvr settings, the boolean field insert background

**Comment by nbessi** [comment]
@PCatinean @diezcode no special char in this pdf...

**Comment by diezcode** [comment]
Problem solved, this was the problem:
![yyyyunbenannt](https://cloud.githubusercontent.com/assets/7522882/6369279/f73b58c4-bce4-11e4-8f5c-781ba32a0bff.PNG)

Because of this input the payment_slip has showed empty. I changed all to "0.00" and it works now

**Comment by nbessi** [comment]
@PCatinean I know i'm sure that you have set bvr delta in company.
As we are in inch now they are all wrong

**Comment by nbessi** [comment]
@PCatinean If you put all to 0 value it should be fine.

I must change the label

**Comment by PCatinean** [comment]
@nbessi it seems diezcode nailed it, that was the root of the problem, all the coordinates were off because of the settings in the backend

**Comment by nbessi** [comment]
Sooo stu***\*  bug as we have inch all values are far too big
