### ISSUE TITLE
Domain is not correctly set in l10n_ch_scan_bvr version 7

### ISSUE THREAD

**Issue by ghost** [OCA/l10n-switzerland#106]
Hello, 

In the module l10n_ch_scan_bvr, in the wizard.scan_bvr.py file the domain is not correctly set
when the function _construct_bvr_postal_in_chf is called. 

This function:

![feature3](https://cloud.githubusercontent.com/assets/9008369/6369583/11652498-bce8-11e4-8cfc-d748914483b4.png)

always return 'bvrnumber': ''.

However, in the code we have:

![feature2](https://cloud.githubusercontent.com/assets/9008369/6369617/677a13e8-bce8-11e4-9f2c-356e857bf46a.png)
![feature_1](https://cloud.githubusercontent.com/assets/9008369/6369618/6780d340-bce8-11e4-9d29-4e311a57906b.png)

So... it always compute bvr_struct['domain'] = 'bvr_adherent_num'

We think that
if bvr_type == '01' and len(bvr_string) == 42:
    bvr_struct['domain'] = 'name' 

while 

if bvr_type == '03':
  domain bvr_struct['domain'] = 'bvr_adherent_num'

**Comment by nbessi** [comment]
@BT-csanchez the issue seems valid @vrenaville can you have a look please.

**Comment by ghost** [comment]
I proposed https://github.com/OCA/l10n-switzerland/pull/111 to solve it, is this ok?
