### ISSUE TITLE
BVR + Invoice in one PDF to be send by email

### ISSUE THREAD

**Issue by lsimonin** [OCA/l10n-switzerland#117]
When users want to send invoices by email, it is possible to bind only a single report.

In the case of ISR it is not possible to send the BVR bills because it would be able to join 2 report.

I propose to create a report that contains the invoice and the BVR (with background image) into a single PDF

**Comment by yvaucher** [comment]
@lsimonin  to answer this requirement, of sending multiple reports as one you could use base_report_assembler: 
https://github.com/OCA/reporting-engine/blob/7.0/base_report_assembler/__openerp__.py

However it is only available in 7.0 for now.

**Comment by lsimonin** [comment]
@yvaucher Thank you for response. Please see this : https://github.com/OCA/l10n-switzerland/pull/126
