### ISSUE TITLE
No bank list on res.partner.bank form from company form

### ISSUE THREAD

**Issue by hmartinet** [OCA/l10n-switzerland#133]
On branch 7.0 with `l10n_ch, l10n_ch_bank, l10n_ch_base_bank, l10n_ch_payment_slip` installed, there is no more bank selectable in the bank field of res.partner.bank form from company form (but there is banks imported by `l10n_ch_bank` in the `res_bank` table in database).
![bank](https://cloud.githubusercontent.com/assets/547774/7721784/a1642416-feda-11e4-93b6-e68107702b87.png)

**Comment by open-net-sarl** [comment]
Hello,
Just type in the first letter of any bank name, and you will see the list coming

**Comment by hmartinet** [comment]
Hello,

Oh ok I'm confused... I did not know that the behavior had changed... Thanks for your response.

Issue solved
