### ISSUE TITLE
[6.1] l10n_ch_zip depends on better_zip

### ISSUE THREAD

**Issue by bodi000** [OCA/l10n-switzerland#152]
Hello,
The rework of l10n_ch package includes a new l10n_ch_zip module. However, it depends on the old better_zip module, which is not present in l10n_switzerland.
Is it a wrong/old dependency, or else where can I find this module?

Thank you,
BS

**Comment by nbessi** [comment]
better_zip should be available here: https://github.com/OCA/partner-contact/ but it seems it is not present in the repo. It is probably a collateral effect of the migration to github. A PR should be done to add the addons in version 6.1

**Comment by open-net-sarl** [comment]
It's there: it has been renamed "base_location" ...

**Comment by nbessi** [comment]
@open-net-sarl not for version 6.1

**Comment by bodi000** [comment]
Yes, I eventually found it... I agree with you that it would be better to
have it on hand, like in good old launchpad times :-)

Thank you,
B
