### ISSUE TITLE
[8.0] Transaction ref in out_invoices not set ?

### ISSUE THREAD

**Issue by ecino** [OCA/l10n-switzerland#165]
I was wondering why out_invoices don't put the bvr_reference in the generated move_lines, is it normal ?

In https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip/invoice.py#L133, we can read that `get_bvr_ref` method handles the out_invoices but this method was removed in version 8.0. Was it intended or not ?

**Comment by ecino** [comment]
@yvaucher

**Comment by yvaucher** [comment]
@ecino BVR reference is computed there. `get_bvr_ref` was removed at https://github.com/OCA/l10n-switzerland/commit/24a9301a02f2eb56d43578e74c8638dee20d7c29

All the logic went in PaymentSlip model.

The field is now `transaction_ref`and not `bvr_reference`

**Comment by yvaucher** [comment]
Note that your partner bank state must be `bv` or `bvr`

https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip/payment_slip.py#L112

**Comment by ecino** [comment]
Ok, thank you.
