### ISSUE TITLE
[8.0] URGENT: l10n_ch_dta both in root AND __unported__

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-switzerland#170]
Can you check this and remove or rename in `__unported__`.

cc/ @yvaucher 

See https://odoo-community.org/groups/contributors-15/contributors-26518?mode=thread&date_begin=&date_end=, item 2 for more information.

**Comment by yvaucher** [comment]
@sbidoul I'll have a look at it

**Comment by yvaucher** [comment]
@sbidoul done at https://github.com/OCA/l10n-switzerland/commit/e5238ac6f8bd57430571d29f02024d6072dc9b65

**Comment by sbidoul** [comment]
Thanks!
