### ISSUE TITLE
Migration 9.0

### ISSUE THREAD

**Issue by yvaucher** [OCA/l10n-switzerland#171]
In order to not port twice the same modules, please comment here if you are going to port a module and tell us about the PR you created.
- [ ] l10n_ch_bank
- [ ] l10n_ch_base_bank
- [ ] l10n_ch_credit_control_payment_slip_report
- [ ] l10n_ch_dta
- [ ] l10n_ch_hr_payroll
- [ ] l10n_ch_import_cresus
- [ ] l10n_ch_payment_slip
- [ ] l10n_ch_payment_slip_layouts
- [ ] l10n_ch_payment_slip_voucher
- [ ] l10n_ch_sepa
- [ ] l10n_ch_states
- [ ] l10n_ch_zip

TODO: add a link on how to port a module from 8.0 to 9.0

**Comment by pedrobaeza** [comment]
This is automatically created by the migration script, so it's not needed to create it manually.

**Comment by open-net-sarl** [comment]
Hello,

We will port l10n_ch_hr_payroll

**Comment by yvaucher** [comment]
@pedrobaeza Ok thanks I'll close this one once the script created it

**Comment by yvaucher** [comment]
replaced by #172
