### ISSUE TITLE
[l10n_ch_bvr_scan] - Improvement/Fix - Remove leading space on BVR string for compatibility with some scanners

### ISSUE THREAD

**Issue by johannbelet** [OCA/l10n-switzerland#193]
Hi, this is more a improvement than an issue but it improve the scanning process a lot in term of speed.

It would be nice to add following code to deal with leading spaces appearing in BVR string when we use some scanners (ex: IRISPen Express 7) :

>    # Get rid of leading and ending spaces of the BVR string
>    bvr_string = bvr_string.strip()

in the following block on line 269

```
...
   def _get_bvr_structurated(self, bvr_string):
       if bvr_string is not False:
           # We will get the 2 first digits of the BVR string in order
           # to now the BVR type of this account
           bvr_type = bvr_string[0:2]
           bvr_struct = {}
           if bvr_type == '01' and len(bvr_string) == 42:
...
```

Regards,

Johann

**Comment by yvaucher** [comment]
Hello @johannbelet this seems a good idea, could you make a pull request to make this change?
