### ISSUE TITLE
How is the DTA workflow?

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#199]
I have some problems with DTA.
I have configurate all with the bank. But know when I want to make a DTA transfer it doesn't work.
Is there any workflow or documentation about that?
Create a DTA works but what are the next steps?
Thank you

**Comment by yvaucher** [comment]
@diezcode depending on your version multiple fixes have landed on dta module

the last one to be added will be #310 

I'm closing this issue, please provide more information if you want to reopen it.
