### ISSUE TITLE
l10n_ch_fds_* should be merged to 9.0 to prepare for porting

### ISSUE THREAD

**Issue by philhug** [OCA/l10n-switzerland#202]

**Comment by yvaucher** [comment]
@philhug Can you do a PR following instruction there to extract the module from 8.0 ?

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0

**Comment by philhug** [comment]
@yvaucher  https://github.com/OCA/l10n-switzerland/pull/205

**Comment by philhug** [comment]
#205 is merged
