### ISSUE TITLE
Impossible to access the runbot log

### ISSUE THREAD

**Issue by ghost** [OCA/l10n-switzerland#214]
Hello,

Unfortunately I cannot access any log of the runbot so It is impossible to know what failed.

[https://www.google.com/url?q=https%3A%2F%2Frunbot.odoo-community.org%2Frunbot%2Fbuild%2F3142117&sa=D&sntz=1&usg=AFQjCNHPjyUiWh8d0nWM2-zGUkCKT4TBtA](url)

Thanks a lot,
Miguel.

**Comment by yvaucher** [comment]
Which runbot for which version of Odoo or in which PR was it for ?
