### ISSUE TITLE
[l10n_ch_payment_slip] bvr_scan_line_letter_spacing never used

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-switzerland#216]
I noticed the field `bvr_scan_line_letter_spacing` is never used inside the code.
So what is this supposed to mean?

Thank you in advance.

**Comment by yvaucher** [comment]
I think it was a field to define letter-spacing parameter as the space between 2 characters in the OCR font.

It seems we use it in a specific that redefines:

```
def _draw_scan_line(...):
    [...]
    textobject.setCharSpace(print_settings.bvr_scan_line_letter_spacing)
```

Not sure we need it though.
