### ISSUE TITLE
Wrong inheritance in l10n_ch_payment_slip_account_statement_base_completion

### ISSUE THREAD

**Issue by stephanamann** [OCA/l10n-switzerland#217]
In File l10n-switzerland/l10n_ch_payment_slip_account_statement_base_completion/wizard/bvr_import.py, line #25 the class is declared to inherit from 'bvr.import.wizard'. In **openerp**.py a dependency to '10n_ch_payment_slip' is declared.

In l10n-switzerland/l10n_ch_payment_slip/wizard/bvr_import.py class BvrImporterWizard is declared and named 'v11.import.wizard'.

So line 25 in l10n-switzerland/l10n_ch_payment_slip_account_statement_base_completion/wizard/bvr_import.py should read:

```
_inherit = 'v11.import.wizard'
```

**Comment by yvaucher** [comment]
`l10n_ch_payment_slip_account_statement_base_completion` has not been ported neither in version 8.0 nor 9.0. Have you a migrated version of l10n_ch_payment_slip_account_statement_base_completion to propose ?

**Comment by stephanamann** [comment]
Sorry, missed your comment from April :-( Yes, we are using this module in odoo version 8. It works just fine, with the change mentioned in my first posting.

**Comment by yvaucher** [comment]
No problem I had some backlog in my messages too :smile: 

Okay in fact this follow this change: https://github.com/OCA/l10n-switzerland/commit/5f5b4e678616d09c2fe8dc2365b8534ff32cbb15

Would you be kind and make a PR with this little change to port the module to 8.0 ?

**Comment by stephanamann** [comment]
Just made the PR.
