### ISSUE TITLE
Account Type not correctly detected

### ISSUE THREAD

**Issue by user1007017** [OCA/l10n-switzerland#243]
Hi, I'm getting the following error:

> The bank account 01-234567-8 used in invoice needs to be a postal account or have a bank CCP.

Installed Odoo 9 and the following "apps"
- Switzerland - Bank list   Camptocamp, brain-tec AG, Odoo Community Association (OCA)  Localisation    9.0.1.0.0
- Switzerland - Bank type   Camptocamp, Odoo Community Association (OCA)    Localization    9.0.1.0.0
- Switzerland - Payment Slip (BVR/ESR)  Camptocamp, Odoo Community Association (OCA)    Localization    9.0.2.1.0

The account number entered at Contacts / Bank Accounts / Bank Accounts was discovered correctly as Postfinance
But after clicking the BVR/ESR button, the message appears

**Comment by dcoopennet** [comment]
I think the issue came from this double negativ check here.
" not " +  " != "
if not bank_acc.acc_type != 'postal' or not bank_acc.ccp:
                    msg.append(_('The bank account {} used in invoice needs to'
                                 ' be a postal account or have a bank CCP.'
                                 ).format(bank_acc.acc_number))
Please fix this as soon as possible.

**Comment by dcoopennet** [comment]
This issue makes the module not working. Please fix this. @yvaucher

**Comment by yvaucher** [comment]
@dcoopennet Can you do a pull request ?

**Comment by yvaucher** [comment]
Fixed by #245
