### ISSUE TITLE
[l10n_ch_payment_slip] Migration issue from v8 to v9

### ISSUE THREAD

**Issue by dcoopennet** [OCA/l10n-switzerland#246]
The views from the module in v8 are not properly removed or replaced by the views of v9.
This cause problem during migration process with Odoo. 

*\* The problem is occurs, seem the module('l10n_ch_payment_slip') change of OCA. During upgrade process we don't clean the OCA module data.
And we don't compare the OCA module change. So you compare the OCA module changes and make your view compatible according to OCA module 9.0.
After make it compatible, try to restore your database with OCA module.**

**Comment by yvaucher** [comment]
@dcoopennet Not sure what is not compatible. It properly installs on a v9.0.

Thus you might want to drop your old view data to rebuild them an update base could do the trick. Unless you have edited the views in web interface in which case you will have to fix it manually.

**Comment by dcoopennet** [comment]
I think a view was customize and set to non-update. Thanks a lot for your answer.

**Comment by yvaucher** [comment]
Ok thus I close this issue, feel free to reopen it.
