### ISSUE TITLE
Exception during V11 (BVR/ESR) Import

### ISSUE THREAD

**Issue by prakashatredcor** [OCA/l10n-switzerland#247]
File "/var/lib/odoo/addons/9.0/l10n_ch_payment_slip/wizard/bvr_import.py", line 195, in _prepare_line_vals
    num = line.invoice.number if line.invoice else False
AttributeError: 'account.move.line' object has no attribute 'invoice'

It may be from followine line of code:
 if line:
            # transaction_ref is propagated on all lines
            partner_id = line.partner_id.id
   **195: num = line.invoice.number if line.invoice else False**
            values['ref'] = _('Inv. no %s') % num if num else values['name']
            values['partner_id'] = partner_id
        return values
           num = line.invoice.number if line.invoice else False

**Comment by yvaucher** [comment]
fixed by #248
