### ISSUE TITLE
Problem while generating a pain.001 file using an IBAN account

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/l10n-switzerland#257]
Hi

Not sure if it's by design or a code error or a problem with the configuration, so here is the situation.

The res.partner.bank info of the supplier is configured with a CCP account of the form "01-xxxxxx-xx".
That means: no IBAN

The res.partner.bank info used to pay this supplier invoice is configured with an IBAN account.

The generated pain.001 XML file that will be uploaded contains among other tags this one: "CdtTrfTxInf".
Under it, there is this structure:

```
<CdtrAcct>
  <Id>
    <Othr>
      <Id>xxxxxxxxx</Id>
    </Othr>
  </Id>
</CdtrAcct>

```

The "xxxxxxxx" value is taken from the "ccp" field that is computed on the supplier's res.partner.bank record.
`>>> file: l10n_ch_pain_base/models/account_payment_order.py, line 101`

I think that the code should rather consider a "cleaned" value of that field, i.e. without the minus signs, because as is, it seems that the file is refused with this error: AC01 (IncorrectAccountNumber)

Thanks in advance.

**Comment by yvaucher** [comment]
Have you made a fix for this one?

**Comment by yvaucher** [comment]
Indeed it is required to have a sanitized number. Still no luck to have a fix for that ?

https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/swiss-usage-guide.pdf

page 18 exemple of creditor account: 010391391
