### ISSUE TITLE
BVR/ESR for UBS Bank accounts / l10n_ch_payment_slip

### ISSUE THREAD

**Issue by whotopia** [OCA/l10n-switzerland#266]
(using latest version of code for Odoo 8)

I have received a number of pre-printed BVR+ forms for my UBS company account. 
These have no client nor amount fields (obviously) in the BVR line  042> 
What I am trying to do based on the data from these form, and UBS guide is to set up BVR invoicing for clients.  

https://www.ubs.com/ch/en/swissbank/corporates/cash-management/downloads/_jcr_content/par/columncontrol_4/col1/linklist_0/link_2.433466627.file/bGluay9wYXRoPS9jb250ZW50L2RhbS91YnMvY2gvc3dpc3NiYW5rL2NvcnBvcmF0ZXMvY2FzaC1tYW5hZ2VtZW50L3BheW1lbnQtc2VydmljZXMvZG9jdW1lbnRzL2hhbmRidWNoLWJlc3ItZW4ucGRm/handbuch-besr-en.pdf

UBS adherent number is 01-145-6 (which is what I put into the BVR Account/IBAN Number Field). This works fine.

I have received a sequence of reference numbers from the bank something like   61909 00001 -> 61909 00xxx
  -- I set up a BVR journal sales account and sequence so that internally to Odoo, I can match this up.

So I'm running into some problems (though I may not fully understand the BVR line specification).

The checksum that Odoo generates for the Referenz-Nr field seems to be 3 digits at the end before the +.  But the standard is 1 digit??? 

So the referenz-Nr, in my case should be:
`>30 xxxxx yyyyy z0006 19090 0xxxC+`

Where `xxxxx yyyyy z` is a variant on my bank account number 

And finally C  is a single digit checksum.

But the best I have managed to do in Odoo is get the referenz-Nr:
`>30 xxxxx yyyyy z0006 19090 0xxxC CC+`

So the module outputs 3 checksum digits, which is not correct???

Can someone advise??????

**Comment by yvaucher** [comment]
This was answered on the mailing list:

https://odoo-community.org/groups/switzerland-29/switzerland-46866

I'm closing it
