### ISSUE TITLE
[9.0]l10n_ch_hr_payroll: .pot translation file does not include hr.salary.rule.xml and many others

### ISSUE THREAD

**Issue by treviser** [OCA/l10n-switzerland#268]
I'm not a developer, so I'm not able to make pull requests.

When I create a .pot file for l10n_ch_hr_payroll, I only get about 6 terms to be translated. All the terms of hr.salary.rule.xml and others are completely missing.
Like I did with the l10n_ch accounting module, which I've sent to @yvaucher  I would like to adapt l10n_ch_hr_payroll in order to:
- set up proper english source terms 
- create a new .pot file
- add proper translations for french, italian and german

Who can adapt l10n_ch_hr_payroll so that it creates a complete .pot file and create the necessary pull requests when I have adapted the translations accordingly?

**Comment by yvaucher** [comment]
Hello,

OCA is in the process of removing .pot files in all modules.
Translations are managed in Transifex and we don't need .pot for that in fact it's a bit more efficient without those files.

Here you will find the values to translate for this module:
https://www.transifex.com/oca/OCA-l10n-switzerland-9-0/translate/#fr/l10n_ch_hr_payroll/79416941

You might need to be logged but you can use your github account to connect to transifex.

@dcoopennet Is the list of term seams correct on transifex ?

**Comment by treviser** [comment]
@yvaucher @dcoopennet I found out why and did rework the whole module. I had to make more fields translatable, see my new issue on this: https://github.com/OCA/l10n-switzerland/issues/270
