### ISSUE TITLE
[9.0]l10n_ch_hr_payroll: remove nb_NO.po, add fr.po and de.po

### ISSUE THREAD

**Issue by treviser** [OCA/l10n-switzerland#269]
I can't see any reason for norwegian language in Switzerland ;-)

**Comment by yvaucher** [comment]
me neither :)

I guess a translator has been overdoing it.

@OCA/community-maintainers Anyone knows if we can restrict localisations to some languages on transifex?
Thus translators won't loose time to translate some texts that will never been used in languages other that english and country languages.

**Comment by pedrobaeza** [comment]
I think it can be the translation memory (one Transifex feature) that autocompletes these languages from other organization projects, so no extra work for any translator. But the bad news are that we can't deactivate languages per project AFAIK. It's handled by organization. But I will make another look to see if possible.

**Comment by yvaucher** [comment]
@pedrobaeza can't we do something with the bot that does the commit ? maybe we could filter at that time

**Comment by yvaucher** [comment]
We could register few langs for all "l10n-*" repositories

**Comment by yvaucher** [comment]
We use Weblate now, this fixed the issue and I removed the files manually in newer branches.
