### ISSUE TITLE
l10n_ch_hr_payroll: Complete rework: multilingual, source terms in english

### ISSUE THREAD

**Issue by treviser** [OCA/l10n-switzerland#270]
I've done a complete rework of the module as following:
- make the fields code, name and note in hr.salary.rule and hr.salary.rule.category translatable
- make the other extra fields of the module translatable
- translate and change all source terms to english
- translate all source terms to french, german and italian

I'm not a developer, so I would greatly appreciate help concerning reviewing, testing and publishing the work, if it is of interest to the community. I have attached the module as zip-File
[tw_l10n_ch_hr_payroll.zip](https://github.com/OCA/l10n-switzerland/files/511344/tw_l10n_ch_hr_payroll.zip)

**Comment by treviser** [comment]
Any comment on this?

**Comment by open-net-sarl** [comment]
This is a great idea to allow translation on salary rule and salary rule category.
But you may have seen that the rules and rule categories are not "updatable".
So if you want to submit your modification please do a pull request on the branch 9.0 of the repository.
I will review this pull request do my best to merge your modifications.

Thanks

**Comment by treviser** [comment]
Unfortunately I don't know how to make a pull request :-(

**Comment by open-net-sarl** [comment]
https://odoo-community.org/page/code you can refer to this documentation.
It was written by the OCA.

**Comment by treviser** [comment]
@open-net-sarl I've done it, see https://github.com/OCA/l10n-switzerland/pull/273
But there is an error: dependency "xlrd" missing...

**Comment by yvaucher** [comment]
I close it a we merged it lastly. thanks for your work @treviser

**Comment by treviser** [comment]
@yvaucher My pleasure, I'm always willing to support the community.
