### ISSUE TITLE
TVA Report V9.0

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/l10n-switzerland#274]
Are you working on a TVA report for the community edition of Odoo ?

**Comment by fclementic2c** [comment]
Hello,

We have not plan on this report today.

Regards,

_camptocamp_

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Frédéric Clementi_
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com

2016-11-01 8:22 GMT+01:00 Open Net Sàrl notifications@github.com:
