### ISSUE TITLE
German Characters not supported

### ISSUE THREAD

**Issue by teamjhuns2014** [OCA/l10n-switzerland#278]
Hi There, 

I am using FPDF to generate payment slip, but problem is German Characters are not getting printed on payment slip pdf correctly. 

Any guide ? 

AJ

**Comment by yvaucher** [comment]
Hello @teamjhuns2014 ,

I don't know FPDF, are you using the module l10n_ch_payment_slip to generate the payment slip and you combine multiple pdf with FPDF? With which version of Odoo?
Once generated with l10_ch_payment_slip your PDF correct has the ä, ö, ü but not after using them with FPDF?
