### ISSUE TITLE
BVR generator Odoo10 not working

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#321]
It doesn't generate a BVR number in Odoo10. I've tried that with all l10n_ch_switzerland module like : bank etc...

Anyone help? what is with l10n_ch_payment_slip? is this ready for odoo10`?

**Comment by yvaucher** [comment]
@diezcode can you provide more information ? Any error shown ? have you any output like an empty pdf ?

https://github.com/OCA/l10n-switzerland/tree/10.0/l10n_ch_payment_slip was migrated. And as far as I know it works.

**Comment by diezcode** [comment]
I need to test it again, I think when I tested it, there wasn't a version for odoo 10.0.
We can close this. On Odoo10 Community it's working fine. thx.
