### ISSUE TITLE
ebics for swiss banks

### ISSUE THREAD

**Issue by davidwul** [OCA/l10n-switzerland#330]
[Ebics is a standard for exchanging](https://www.six-interbank-clearing.com/dam/downloads/en/clearit/70/ebics.pdf) file between the enterprise software and the banks. This seems similar to FDS postfinance but it's accross different banks. 
This thread is to federate a potential development around that. At least a few banks are enforcing it (UBS/Credit suisse/raiffeisen and more)
Here is a few resources:

- [python library with a odoo module](https://www.dumaine.me/wordpress/?p=419#comment-1293) (french implementation but quite old) 
- bank test with [ebics interface](https://isotestbank.raiffeisen.ch/corporates/) (raiffeisen) quite easy to register
- [ebics website](http://www.ebics.org/home-page/) for technical informations
- [Swiss Market Practice Guidelines EBICS](https://www.six-interbank-clearing.com/dam/downloads/de/standardization/ebics/ebics.pdf) from SIX in German.

**Comment by yvaucher** [comment]
I add this here:

"EBICS and ISO 20022:  
More than just the sum of their parts"
https://www.six-interbank-clearing.com/dam/downloads/en/clearit/69/ebics.pdf
