### ISSUE TITLE
Error while printing ESR

### ISSUE THREAD

**Issue by giordano-ch** [OCA/l10n-switzerland#358]
Hi

I have a little problem with the payment slip module. It works perfect, until i print the ESR than i get this error:

'bool' object has no attribute 'encode': (<type 'exceptions.AttributeError'>, AttributeError("'bool' object has no attribute 'encode'",), <traceback object at 0x7fc2c99e27a0>)

has anabody got this error before?

Thanks in advance

**Comment by yvaucher** [comment]
@giordano-ch this errors means you should have a variable filled with a string. It can be a field which is not properly set. Do you have the full error stack trace ?

Plus specify which version of Odoo you have.
