### ISSUE TITLE
[10.0] constrain on bank account and partner doesn't play well with some vendor invoice

### ISSUE THREAD

**Issue by davidwul** [OCA/l10n-switzerland#376]
I guess we are not alone facing the issue with the bank account constrain in v10.
When vendors send invoices with the "account" of the ISR (BVR/ESR)  as the postal account of the bank.  And vendor has the same bank, the constrain refuse to create the account in the second vendor as the bank account already exist. How do you handle this, do you simply remove the constrain or is there a way to change this? Thanks for your help and idea?

Same issue with the ref constrain. Some vendor send the same ISR line each month, anybody have a solution to that? For now, we are just adding zero in front of the reference but this is not ideal?

**Comment by yvaucher** [comment]
For versions version 11.0 and older, when your suppliers gives you an ISR-B, the ccp (postal account number) must be filled at the Bank level (res.bank).

For later version use the `l10n_ch_postal` field on `res.partner.bank`.
