### ISSUE TITLE
master 8.0 is not up to date

### ISSUE THREAD

**Issue by nbessi** [OCA/l10n-switzerland#38]

**Comment by thomich** [comment]
is there any plan, at which time 7.0 modules are migrated to 8.0?

**Comment by yvaucher** [comment]
@thomich no plan yet to migrate them to 8.0

You are welcome to contribute

**Comment by thomich** [comment]
Hey hey....
we have made a migrated version for Odoo 8 for:
l10n_ch_base_bank and l10n_ch_payment_slip
https://bitbucket.org/thomi/odoo-tools-8.0/src

Maybe we can push it to OCA/l10n-switzerland

**Comment by nbessi** [comment]
@thomich Nice of you to propose  the work. 

The port of the localization was planed on community list.
There already is a PR for base_bank and DTA.  Account_payment_slip is currently ported to New API and QWeb report. 

It is a shame that your fork was not more visible. 

The other addons are also on the go, please refer to community mailing list:
https://lists.launchpad.net/openerp-community/msg06931.html

Regards

Nicolas

**Comment by thomich** [comment]
Sorry for confusion or feeling we hide our work, but we have customers that are needing it.
My idea was to finish migration and tests and then post here to find a way to push into OCA/l10n_switzerland...

Was not my idea to hide it.. sorry.. ;)

We migrated the report also to Qweb, but not to new API, cause we only migrated those two modules, which are independent from the others...

Cheers
Thomas
