### ISSUE TITLE
[10.0] Zip and City inversed

### ISSUE THREAD

**Issue by magneticlab-ch** [OCA/l10n-switzerland#389]
There is a strange bug.

When printing the BVR with the adminsuer, the formated address under reference is set correctly (ZIP +CITY). But when we choose a standard user and print the BVR, the adderss format is inverted (city+zip)!

ex: superuser
00 00000 00000 00000 00000 00000
name
street
**2400 Le Locle**

ex: normal user
00 00000 00000 00000 00000 00000
name
street
**Le Locle 2400**

how could that be possible? (V10 instance)

**Comment by treviser** [comment]
I assume this is either an issue for the help forum or else you did not provide enough information for a bug report. 
Did you properly set the address format at "Sales/Configuration/Contacts/Countries/Switzerland", and is the country properly assigned to the corresponding contact?

**Comment by yvaucher** [comment]
As @treviser said this depends on the country config.

But there was also a bug depending on the access right which wouldn't take the country address format and would take the default one instead. A fix was applied lastly.

Please try with the last version: 10.0.1.1.2
