### ISSUE TITLE
CH Payroll: update parameter default values in the payroll configuration

### ISSUE THREAD

**Issue by treviser** [OCA/l10n-switzerland#390]
Just for the convenience: please update the following parameter defaults according to the new legal values:

- OAI/II/IC: 5.125%
- OBP minimum legal: 1,767.633
- UI Maximum limit: 12350

Thanks!

**Comment by didierdonze** [comment]
- OAI/II/IC: 5.125%
-> I agree
- OBP minimum legal: 1,767.633
-> The annual minimal salary amount to contribute is 21150 (monthly 1762.5)
- UI Maximum limit: 12350
-> I agree

**Comment by treviser** [comment]
> OBP minimum legal: 1,767.633
> -> The annual minimal salary amount to contribute is 21150 (monthly 1762.5)

I agree, stupid me :-)

**Comment by asaunier** [comment]
@treviser Feel free to have a look at PR #394 for Odoo 10.

Are the changes required for Odoo 9 as well?

It seems some values had already been updated.
For instance https://github.com/OCA/l10n-switzerland/blob/9.0/l10n_ch_hr_payroll/data/hr.salary.rule.xml#L108 (UI maximum limit)

On the other hand the LPP min seems to be outdated:
https://github.com/OCA/l10n-switzerland/blob/9.0/l10n_ch_hr_payroll/data/hr.salary.rule.xml#L211
Ditto for OAI:
https://github.com/OCA/l10n-switzerland/blob/9.0/l10n_ch_hr_payroll/data/hr.salary.rule.xml#L70

Proposed changes for version 9: https://github.com/OCA/l10n-switzerland/pull/395

**Comment by asaunier** [comment]
PRs for both Odoo 9 and 10 have been merged.
