### ISSUE TITLE
CH Payroll: Payroll Configuration domains do not allow to use proper accounts according to the official Swiss Chart of Accounts

### ISSUE THREAD

**Issue by treviser** [OCA/l10n-switzerland#391]
I'm struggling with coordinating the logic behind the new Payroll Configuration and the payroll description according to https://www.open-net.ch/blog/odoo-en-suisse-11/post/calcul-des-salaires-suisses-avec-odoo-118
As far as I understand it, the account 5801- Compte de compensation- (which does not exist in the official Swiss Chart of Accounts (anymore, if it ever existed)) should be replaced with the account 1091 - Compte d'attente pour salaires. This is not possible due to the domain filters applied to the corresponding fields.

For a better understanding it would be helpful to get some more information in the description, I'm willing to help, but I would need some more information, it could also be in french.

**Comment by open-net-sarl** [comment]
You can use another account as 5801 as long as you have a class 5 account with type 'Expenses'.

It should not be a 1091 account as it will hold the small computation difference, so it must be in the 'Profit and Loss' report
