### ISSUE TITLE
bvr_scan_line_letter_spacing not working

### ISSUE THREAD

**Issue by magneticlab-ch** [OCA/l10n-switzerland#393]
Hello all,
Concern: a parameter `bvr_scan_line_letter_spacing` which is available in the company settings when the module "l10n_ch_payment_slip" is installed.
AFAIK this parameter is not used in the module.
Is there a plan to use it ? or a workaround ?

PS: we use V10.
Thank you.

**Comment by yvaucher** [comment]
@magneticlab-ch well spotted, seems it was dropped since the refactor from version 7.0 to version 8.0

This is clearly a bug. Either we want to restore this feature or to remove the field.

Did you had some trouble with the default spacing?
