### ISSUE TITLE
SEPA Credit Transfer is not compatible with all swiss banks.

### ISSUE THREAD

**Issue by ghost** [OCA/l10n-switzerland#412]
The Züricher Kantonalbank (https://www.zkb.ch) does not follow the ISO standard and implements the required (optinal) tag &#60;InstrId&#62; as mandatory instead.
pain.001.001.03.ch.02 states that &#60;InstrId&#62; is required and multiplicity is documented as 0..1.
I got the answer from ZKB that they need the element to give a response with transaction id in case of error. That would help the user to identify the problem more easily.

See page 31 of Swiss Implementation Guidelines ( https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf ) and XSD (pain.001.001.03.ch.02.xsd) is mentioned in same document on page 52 ( https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct-examples.zip )
My exported XML-pain file was unsuccessfully tested on ZKB test platform ( https://testplattform.zkb.ch ).
Other swiss banks returned no problems, just hints that element &#60;InstrId&#62; should be used.

&#60;CdtTrfTxInf&#62;
..&#60;PmtId&#62;
....&#60;InstrId&#62;XXX&#60;/InstrId&#62; &#60;!-- required by ZKB --&#62;
....&#60;EndToEndId>XXX&#60;/EndToEndId&#62;

**How to reproduce**

Create a SEPA payment order.
Create xml-pain file.
Upload xml-pain file to validation platform of Zürich Kantonalbank ( https://testplattform.zkb.ch ).

**Expected behaviour**

Exported pain file can be validated by all swiss banks.

**Possible Fix**
Add statement for "InstrId" like for "EndToEndId". I recognized that line.name is unique because is is composed of "L" and the bank_statement_line.id. Therefore it might be sufficient to just copy that part of the code and change the tag name.
https://github.com/OCA/bank-payment/blob/9.0/account_banking_sepa_credit_transfer/models/account_payment_order.py#L129-L133

**Comment by ghost** [comment]
see also
https://github.com/OCA/bank-payment/issues/465

**Comment by thomich** [comment]
Hello

InstrId is recommended and also Mandatory by Basler Kantonalbank, else they reject the payment.
Check also https://www.six-interbank-clearing.com/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf on page 31, definition of InstrId.

Thanks for updating it..

Regards
thomi

**Comment by thomich** [comment]
Hello

reading and testing around and that would be my solution:
![image](https://user-images.githubusercontent.com/4398840/41541649-3dbb2968-7313-11e8-9327-bbe129965b41.png)

what others think?
thomi

**Comment by sbidoul** [comment]
Note InstrId is not added by the base module (same value as EndToEndId)
