### ISSUE TITLE
[11.0] [URGENT] l10n_ch_base_bank - Error on compute

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/l10n-switzerland#415]
The method `_compute_acc_type` from module `l10n_ch_base_bank` is not prepared for multiple res_partner_bank records.
(_`https://github.com/OCA/l10n-switzerland/blob/11.0/l10n_ch_base_bank/models/bank.py#L194`_)

Should be `rec.acc_number` and not `self.acc_number`, this causes the error "Expected singleton".

**Comment by yvaucher** [comment]
This was fixed by #417
