### ISSUE TITLE
Print Swiss BVR/ESR problem

### ISSUE THREAD

**Issue by loicbaechler** [OCA/l10n-switzerland#42]
Hi,

Everytime we are trying to print the BVR from "customer invoices" on our Odoo 7 installation we got the following error :

```
Rendu webkit !
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/openerp-7.0-py2.7.egg/openerp/addons/report_webkit/webkit_report.py", line 274, in create_single_pdf
**self.parser_instance.localcontext)
File "/usr/local/lib/python2.7/dist-packages/Mako-0.7.3-py2.7.egg/mako/template.py", line 412, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/local/lib/python2.7/dist-packages/Mako-0.7.3-py2.7.egg/mako/runtime.py", line 766, in _render
**_kwargs_for_callable(callable_, data))
File "/usr/local/lib/python2.7/dist-packages/Mako-0.7.3-py2.7.egg/mako/runtime.py", line 798, in _render_context
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/local/lib/python2.7/dist-packages/Mako-0.7.3-py2.7.egg/mako/runtime.py", line 824, in _exec_template
callable_(context, *args, **kwargs)
File "memory:0x7f80f855c7d0", line 287, in render_body
<%
IndexError: list index out of range
```

List of installed modules: 
Switzerland - Bank Payment File (DTA)   l10n_ch_dta 7.0.1.0
Switzerland - Payment Slip (BVR/ESR)    l10n_ch_payment_slip    7.0.1.2
Financial Reports - Webkit          account_financial_report_webkit 7.0.1.0.2
Switzerland - Accounting                l10n_ch 7.0.7.1
Contracts Management                account_analytic_analysis   7.0.1.1
Switzerland - Bank type             l10n_ch_base_bank   7.0.1.1
Webkit Report Engine                report_webkit   7.0.0.9

Has somebody one idea ?

Best reagards

Loic

**Comment by yvaucher** [comment]
Thanks for reporting

Which version of wkhtmltopdf do you use ?

**Comment by loicbaechler** [comment]
I use the version 0.12.0

**Comment by mdietrichc2c** [comment]
Hello Loic,
is the wkhtmltopdf path set correctly in Settings -> Technical -> Parameters -> System Parameters, variable "webkit_path"? Is it using the i386 or the amd64 library?

Or are you using the one present in /usr/bin/wkhtmltopdf ?

**Comment by soriyath** [comment]
Hi there,

I have the same issue. Tried with the package supplied by apt-get, as well as the ones supplied by wkhtmltopdf (version 0.9.9 and 0.12.1, 64 bits). I added the key webkit_path in system parameters, with the value /usr/bin/ (i copied the supplied binaries from /usr/local/bin/).

I still have the same issue.

**Comment by nbessi** [comment]
Hello, 

Without acces to your installation debug will probably not be possible

Regards
Nicolas

**Comment by willArrive** [comment]
Hello,
I have some error after installing BVR module for Switzerland. I modified it for odoo v8. But I have an error when I want to print.
See the following attached document :

![image](https://cloud.githubusercontent.com/assets/8824817/5524866/c6d964cc-89dc-11e4-843b-734d4a651768.png)

Any help will be appreciated,
Séraphine

**Comment by guewen** [comment]
Hello,

What do you mean by:

> I modified it for odoo v8.

?

**Comment by willArrive** [comment]
I change the code for odoo v8. And I installed it on my odoo v8. I see the BVR/BSR under Menu "PRINT".
But when I click it open the error window.

**Comment by nbessi** [comment]
The new code for version 8 is availbabe here.

https://github.com/OCA/l10n-switzerland/pull/65

Nicolas
