### ISSUE TITLE
[11.0] l10n_ch_base_bank : 5-digit account number automatically sets partner bank to 'postal' even for non-Swiss customers/banks

### ISSUE THREAD

**Issue by MaxyMoos** [OCA/l10n-switzerland#439]
How to reproduce:

- Install _l10n_ch_base_bank_ and _l10n_ch_bank_
- In Accounting, create a new Customer from a foreign country and add a Bank Account to it
- Enter any 5 digit number as the account number

=> The bank account type is automatically set to `postal`, CCP field is set to the 5-digit value and the bank is set to "PostFinance AG".

This is an issue that appears when handling foreign customers that unfortunately happen to have 5 digit numbers as their account numbers.

Tested on Odoo 11.0 (commit [a19d2c9](https://github.com/odoo/odoo/commit/a19d2c98f4c80d162a92d08ce4a43ca6021f3bca))

**Comment by yvaucher** [comment]
Have you worked around this issue in the (long) mean time?

It was originally intended. As the 5 digits number is an old valid format:

https://github.com/OCA/l10n-switzerland/blob/11.0/l10n_ch_base_bank/models/bank.py#L41

IMO we can remove it.

EDIT: in version 12.0 we already removed it.
