### ISSUE TITLE
Cannot see bank BVR options in bank view form

### ISSUE THREAD

**Issue by yvaucher** [OCA/l10n-switzerland#44]
Just installed l10n_ch_payment_slip and bvr_adherent_num is not visible in bank form.

**Comment by open-net-sarl** [comment]
Hello,
Did you check that the type of bank account is 'BVR' ?

**Comment by yvaucher** [comment]
@jaeberhard This is a note to myself as there was an issue when installing it from github fields_view_get output was correct but nothing was changing dynamically in the view. I must check this with a newer version of Odoo 7.0
