### ISSUE TITLE
[11.0] l10n_ch_payment_slip: "Generate missing terms" fails because README.md contains '\n' characters

### ISSUE THREAD

**Issue by MaxyMoos** [OCA/l10n-switzerland#440]
Can be reproduced on http://3337682-11-0-34b777.runbot1.odoo-community.org/

**How to reproduce**
* Have _l10n_ch_payment_slip_ in the list of modules - not necessarily installed
* Go to _Settings_ > _Translations_ > _Generate Missing Terms_ for the English language (need to activate Developer Mode)

**Result**
* An error is thrown after a while :
```AssertionError: Translation terms may not include escaped newlines ('\n'), please use only literal newlines!```

After analysis, this seems to be due to the content of the README.md file.
I tried double-escaping those "\n" strings in the README.md but to no avail.

**Comment by yvaucher** [comment]
PO file have been regenerated since them. -> closing this issue

Thanks
