### ISSUE TITLE
[10.0] pain001 generated file is not valid.

### ISSUE THREAD

**Issue by anedisi** [OCA/l10n-switzerland#461]
The pain file generated is not valid with six documentation

the generated file has AdrLine and PstCd and when i upload it to postfinance test platrform i get the error. 

`The structure of the XML element /Document/CstmrCdtTrfInitn/PmtInf[1]/CdtTrfTxInf[1]/Cdtr/PstlAdr is not valid.
    Error message:
        Structured address data should not be used together with unstructured data.
    Error code:
        CH16 (ElementContentFormallyIncorrect)
    File position:
        Line:   58
        Column: 19`

The documentation says.

`If possible structured.
Simultaneous use of the structured elements <StrtNm>/<BldgNb>/
<PstCd>/<TwnNm> and the unstructured element <AdrLine> is not
permitted.`

as seen in generate_party_block -> account_payment_order.py the code will generate AdrLine and PstCd, TwnNm it those fields are present

```
if partner.country_id:
    postal_address = etree.SubElement(party, 'PstlAdr')
    if gen_args.get('pain_flavor').startswith(
            'pain.001.001.') or gen_args.get('pain_flavor').startswith(
            'pain.008.001.'):
        if partner.zip:
            pstcd = etree.SubElement(postal_address, 'PstCd')
            pstcd.text = self._prepare_field(
                'Postal Code', 'partner.zip',
                {'partner': partner}, 16, gen_args=gen_args)
        if partner.city:
            twnnm = etree.SubElement(postal_address, 'TwnNm')
            twnnm.text = self._prepare_field(
                'Town Name', 'partner.city',
                {'partner': partner}, 35, gen_args=gen_args)
    country = etree.SubElement(postal_address, 'Ctry')
    country.text = self._prepare_field(
        'Country', 'partner.country_id.code',
        {'partner': partner}, 2, gen_args=gen_args)
    if partner.street:
        adrline1 = etree.SubElement(postal_address, 'AdrLine')
        adrline1.text = self._prepare_field(
            'Adress Line1', 'partner.street',
            {'partner': partner}, 70, gen_args=gen_args)
```

So my question is, how to i go about overwriting this, best place is to overwrite it in l10n_ch_pain_credit_transfer in generate_party_block -> account_payment_order.py  ?

Im new to odoo so sorry if there is somewhere answer to this question.

**Comment by tm-up** [comment]
I ran into the same using odoo 11. Odoo 8 emitted "StrtNm" instead of "AdrLine", which was compatible with SIX. 
What I did: I've changed the tag 'AdrLine' to 'StrtNm' and moved the corresponding if-block up to  line 3 (before the "if gen_args...."). That fixed the issue. However, it might break things for non-swiss users...

**Comment by yvaucher** [comment]
This was fixed in
[10.0] https://github.com/OCA/l10n-switzerland/pull/477
[11.0] https://github.com/OCA/l10n-switzerland/pull/483
