### ISSUE TITLE
l10n_ch_account_tags do not contain the correct account ids

### ISSUE THREAD

**Issue by fclementic2c** [OCA/l10n-switzerland#464]
This module adds up tags to account (from l10n_ch module) using the id (ie: ch_coa_1091).
However, when I install l10n_ch on Odoo 11ce (I did not try other versions) I notice that the ids looks like 
1_ch_coa_1091. 
Odoo seems to add the company id (1 in my example) as a prefix so the link cannot work anymore and this module becomes useless since tags are not added to accounts.

Rq: this is mainly use for https://github.com/OCA/l10n-switzerland/tree/11.0/l10n_ch_mis_reports. These reports are built on formulas based on account tags

**Comment by fclementic2c** [comment]
I add that we should also change the data file from XML to CSV to comply with odoo philosophy: https://github.com/odoo/odoo/pull/28888/files

**Comment by leemannd** [comment]
Adressed in https://github.com/OCA/l10n-switzerland/pull/489
