### ISSUE TITLE
[10.0] Cannot compute the Payment Information Identification

### ISSUE THREAD

**Issue by ecino** [OCA/l10n-switzerland#480]
Hello @p-tombez @yvaucher . Since the merge of #408, we have crashes on our database when generating pain files. It seems that when evaluating the `payment_info_ident` variable, both values `optional_args` and `category_purpose` are not present in the `eval_context` and this is crashing the operation. Can I ask why is this inheritance overriding completely the `payment_info_ident`? I have the feeling that something is wrong with this way of doing and does not preserve well the behaviour across the inheritances of the function.

I should add that we are generating postfinance dd files using the l10n_ch_lsv_dd module that calls directly the method `generate_start_payment_info_block` https://github.com/OCA/l10n-switzerland/blob/d3b94054863c9110c971e6e59880a64bcb6eb8e1/l10n_ch_lsv_dd/models/account_payment_order.py#L479

**Comment by yvaucher** [comment]
@ecino indeed #408 requires changes introducted in https://github.com/OCA/bank-payment/pull/462

You need to upgrade your version of account_banking_sepa_credit_transfer.
