### ISSUE TITLE
l10n_ch_zip obsolete?

### ISSUE THREAD

**Issue by guewen** [OCA/l10n-switzerland#496]
Some facts:

* l10n_ch_zip is based on a hardcoded data file extracted from files published by post.ch which seems to not exist anymore (https://github.com/OCA/l10n-switzerland/blob/b6af23651744e1e1cbc3e128952b9e269103d3f4/l10n_ch_zip/models/city_zip.py#L10-L14)
* [base_location_geonames_import](https://github.com/OCA/partner-contact/tree/11.0/base_location_geonames_import) does a better job at importing city, zip and states with more recent and complete data (no states in l10n_ch_zip for instance)
* Additionally to loading data, the addon adds some CH specific fields to `res.city.zip` (onrp, communitynumber_bfs, ...). I'm not sure that we can find these data with geonames, but I'm not sure we need these fields at all

Should we deprecate l10n_ch_zip entirely in favor of base_location_geonames_import?
I would be in favor of doing it.

**Comment by yvaucher** [comment]
Never saw a use for the specific fields. It sound a good idea to me to remove l10n_ch_zip and relies only on base_location_geonames_import.
