### ISSUE TITLE
[12.0] SEPA Credit Transfer <PstCd> and <TwnNm> are not compatible with swiss banks

### ISSUE THREAD

**Issue by giordano-ch** [OCA/l10n-switzerland#507]
In version 12 of l10n_ch_pain_credit_transfer <PstCd> and <TwnNm> are always generated in the XML File. 

According to UBS testplatform, the concurrent use of PstCd/TwnNm with the unstructured element AdrLine is not allowed.
![image](https://user-images.githubusercontent.com/15436224/63943145-5c495080-ca6f-11e9-87b5-4a71daecc790.png)

We have tested this with various swiss banks such as UBS, Credit Suisse and Kantonalbank and the upload always gets refused.

If we comment out the tags, the generation of the XML doesn' work anymore.

Has anyone a fix for this?

**Comment by diezcode** [comment]
seems that this issue is fixed in odoo11 ?? any information about this?

**Comment by yvaucher** [comment]
We should be using AdrLine instead.

This was fixed for odoo11 in https://github.com/OCA/bank-payment/pull/583/files

With the following change for l10n_ch:

https://github.com/OCA/l10n-switzerland/blob/11.0/l10n_ch_pain_base/models/account_payment_order.py#L107-L129

I just cherry-picked those 2 commits into 12.0

https://github.com/OCA/l10n-switzerland/commit/4cab9412bc241a85ab0ecc5fe70be185e621d598#diff-5d36e3d6e4ebf67a6a0490d4a52478d0
https://github.com/OCA/l10n-switzerland/commit/ecca11c1de7b05e9dd6f24c7a8cd6862d7905214#diff-5d36e3d6e4ebf67a6a0490d4a52478d0

**Comment by yvaucher** [comment]
Seems the cherry-pick don't have any effect it seems https://github.com/OCA/bank-payment/pull/583/files didn't make it into 12.0 branch of bank-payment.

Will propose a PR for that as well.

**Comment by yvaucher** [comment]
PR for bank-payment made here: https://github.com/OCA/bank-payment/pull/627

@giordano-ch 
So you need to patch your 'bank-payment` plus pull last version of this repository.

**Comment by giordano-ch** [comment]
@yvaucher thanks for quick feedback. Is this issue fixed now? 
I pulled the newest repository 'l10n_ch' and 'bank_payment' but the Tags <PstCd> and <TwnNm> are still generated

**Comment by yvaucher** [comment]
@giordano-ch OCA/bank-payment#627 was merged 6 days ago, please retry :)
