### ISSUE TITLE
Allow duplicate account-Nr for Swiss payment-slip?

### ISSUE THREAD

**Issue by rgl1234** [OCA/l10n-switzerland#511]
Hello
We often have the situation, that swiss payment-slip use the same postal-account-nr for different customers. When we try to create a payment like that, Odoo generates an error, because by default it is not allowed to have the duplicate of account-nrs....account-nr has to be unique per default what is not the case always with swiss payment-slip.
How can this be solved?
Should maybe the constraint be removed to handle those situations?
Thanks
rené

**Comment by yvaucher** [comment]
Hello @rgl1234,

This occures in case of ISR-B, when multiple of your suppliers or customers (for refund) are at the same bank. Thus they provide you the same postal account number.

In version til Odoo 11.0 You want to have the module `l10n_ch_base_bank` installed and handle this by using the field `ccp`.
In version from Odoo 12.0 and later you will have to fill the field `l10n_ch_postal` and set whatever you want in the `acc_number` field.

We don't want to remove the constraint to avoid other issues, this is why we created a second field.

Those fields are only available from the form view of the bank account, you have to go in "Contact"->"Configuration"->"Bank accounts"

**Comment by rgl1234** [comment]
> In version til Odoo 11.0 You want to have the module `l10n_ch_base_bank` installed and handle this by using the field `ccp`.
> In version from Odoo 12.0 and later you will have to fill the field `l10n_ch_postal` and set whatever you want in the `acc_number` field.

Thans for your reply.
I understand...So is it the same in V11 and V12 that the value of "acc_number" is not relevant in those cases?

**Comment by rgl1234** [comment]
Hello @yvaucher 
I just tested it on V12. When I set to "acc-number" field to whatever I want,  the field "l10n_ch_postal" always changes automatically to that value and field "acc_type" back from "postal" to "bank". Then I could change "l10n_ch_postal" back to the correct postal-value but still "acc_type" remains on "bank".
So this seems to be confusing for me....
Or am I understanding something wrong here?

**Comment by rgl1234** [comment]
I also tried to generate Payment-XML in V12-online but receive error-messages because of not recognized IBAN. So it seems not to work if "acc_type" is <> "postal" because value in XML is coming from "acc_number" and not from "l10n_ch_postal".
Is this maybe a general problem in l10n_switzerland?

**Comment by yvaucher** [comment]
@rgl1234 The issue with the onchange on acc_number comes from odoo core. I have disabled this behavior with last changes in l10n_ch_base_bank:
https://github.com/OCA/l10n-switzerland/blob/12.0/l10n_ch_base_bank/models/bank.py#L209-L211

I also created a fix for that on odoo master branch:
https://github.com/odoo/odoo/pull/35979
