### ISSUE TITLE
l10n_ch_base_bank should not depend on l10n_ch

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/l10n-switzerland#528]
a swiss company may have a completely different accounting plan than the default l10n_ch but still need the swiss banks.
if l10n_ch_base_bank is not really technically depending on l10n_ch, that dependency should be removed from the manifest file.

**Comment by yvaucher** [comment]
@Martronic-SA Issue is that the Odoo core module now includes more than the Chart of account.

Your assertion was true for version <12.0

https://github.com/odoo/odoo/blob/91560fae56f1cba09141eefa1d0da03f4a7b3f72/addons/l10n_ch/models/res_bank.py#L26-L36

**Comment by yvaucher** [comment]
What you want is to avoid to generate automatically the CoA. The template on itself is not an issue.

It's a bit tricky but possible to avoid Odoo to install automatically the CoA from the template on module's installation.

What you can do is to create a single account.account on your company. Before installing l10n_ch. It will consider you already have a CoA installed and won't copy the template as CoA.

Warning, installing `account` module with your company set with CH country will also automatically install `l10n_ch`
https://github.com/odoo/odoo/blob/12.0/addons/account/__init__.py#L13

**Comment by Martronic-SA** [comment]
Ok I see. But banks and CoA might (should?) have been added in two separate modules as long as they concern two different things not linked together (except that they are both for Switzerland).
In my particular case I just wanted to uninstall the swiss CoA but keep swiss banks.

**Comment by yvaucher** [comment]
I know, Odoo have been a bit un-flexible about it due to their stable policy, you can try to contact them about this but they will most likely change nothing before Odoo 14.0.

**Comment by Martronic-SA** [comment]
Yes I understand that it's difficult to change now that te module l10n_ch has been published like that.
I keep that issue open for the moment as so we can think about it for the future releases.
