### ISSUE TITLE
Add a way to re-use payment slip on a Qweb report

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/l10n-switzerland#530]
Actually, `PaymentSlip._draw_payment_slip()`, in `l10n_ch_payment_slip/models/payment_slip.py:828`, only return a finished PDF document.
This prevent payment slip to be include in a standard Qweb report.

It would be great to add a possibility to use a payment slip on a Qweb report.

**Comment by yvaucher** [comment]
Have you seen module `https://github.com/OCA/l10n-switzerland/tree/12.0/l10n_ch_invoice_with_payment` ?

By the way, note that ISR payment slip will be replaced by QR-invoice in may 2020

**Comment by sebastienhasa** [comment]
@yvaucher: Thanks. :)

After looking at the code of `l10n_ch_invoice_with_payment`, when you render the report "Invoice with payment slip", the code simply render the invoice and the payment slip, then merge it with `merge_pdf_in_memory()`.
This method is added to the model `ir.actions.report` at `l10n_ch_payment_slip/report/ir_action.py:L151`.

So, if someone need to add a payment slip on a Qweb report, he can simply draw inspiration from the code at `l10n_ch_invoice_with_payment/models/report.py:L11`.

It would by nice to document it, somewhere easy to find. ;)
