### ISSUE TITLE
can't configure postfinance ebill

### ISSUE THREAD

**Issue by davidwul** [OCA/l10n-switzerland#716]
I don't know where to find help or if it's a bug. 
I'm trying to configure the ebill postfinance, 
but the test connection is failing, 
I used the credential provided to log in to https://einvoicing-ki.postfinance.ch/

zeep.exceptions.Fault: Unknown Username or incorrect Password

Any idea where it's wrongly configured?
Thanks for any help,

**Comment by TDu** [comment]
Hello @davidwul, 
The credentials to use with the web service are different than the one for the poral.
You may need to request them from Postfinance.

**Comment by davidwul** [comment]
Wonderful, thanks, that's indeed the issue. 
I can log in, and send invoices, 
Is the lookup (get_ebill_recipient_subscription_status) implemented from the odoo menus, or how is this supposed to work?

**Comment by TDu** [comment]
The update of the subscription status has not been implemented, yet. Not sure if it was ready at the time of development.
May look at this soon...
