### ISSUE TITLE
Payroll configuration error

### ISSUE THREAD

**Issue by nbessi** [OCA/l10n-switzerland#74]
Comment from @stevech091

Hello @open-net-sarl after my short test you have seen that you have configured AVS company contributor double of employ but I think is a mistake. Normally the company contributor are the same of employ (all my customer HR software have this configuration).

In your http://ur1.ca/ir5ou you talk about "Impôt à la source" in "montant fixè". Why? I think in better use some formula and table. In Ticino "Impôt à la source" are on years base (not montly) so is very hard for end user calculate every month the new "montant".
What do you think?

Work for other test.

Regards,

Stefano

**Comment by open-net-sarl** [comment]
Hi,
It's correct that, most of the time, we have the same amount as company contribution and employee contribution. And this is what does the module even if you may have the impression it doesn't.

Let me try to explain.
I have a 'BASIC' salary and I need to take 5,15% away, so I have the first rule, taking this amount away and I can print it in the payroll slip for the employee.
Now, I need to compute  the TOTAL amount to be paid to te AVS caisse, which is the second rule.
Obviously, this amount will be double as it's include the employee and employer part.
This amount will match the invoice to be received from AVS.
This is the method implemented, which I think is correct.
But we will rename the 'second rule' to be 'Total contribution' and not 'Company contribution'.
I put also some more info here 
http://open-net.ch/blog/odoo-version-8-5/post/comptabilite-salariale-suisse-58

**Comment by yvaucher** [comment]
cc @stevech091
