### ISSUE TITLE
l10ch_payment_slip: scan line must not contain whitespaces

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-switzerland#82]
Impacted versions:
- https://github.com/OCA/l10n-switzerland/pull/65

Steps to reproduce:
1. install module 'l10n_ch_payment_slip from https://github.com/nbessi/l10n-switzerland/tree/new_payment_slip
2. create a new customer invoice
3. print the 'Payment Slip' report

Actually, scan line is using 'BVR/ESR Ref' as is, without remove whitespaces before according to https://www.postfinance.ch/binp/postfinance/public/dam.q66fKuNGU4w8QsUdebHtUSDrZmx_vJVUoy2Yp7fkNL4.spool/content/dam/pf/de/doc/consult/manual/dlserv/inpayslip_isr_man_it.pdf (see image at pag. 8)

**Comment by nbessi** [comment]
:+1: thanks for the patch
