### ISSUE TITLE
res.bank should store the Branch ID

### ISSUE THREAD

**Issue by omacchioni** [OCA/l10n-switzerland#83]
the clearing number is not sufficient to identify a bank.

Cf the doc: http://www.six-interbank-clearing.com/dam/downloads/en/bc_bank_master/bc_records.pdf

"Together with the BC number the branch ID provides a conclusive key for
each entry. "

**Comment by nbessi** [comment]
Hello 

We will add the field in branch 8.0. https://github.com/OCA/l10n-switzerland/pull/69/files#diff-11d61938e3d2f68acbe0bb0c258ccfe2R49

The branch 7.0 is now  under maintainance mode. We ll try not to alter data model. 

Regards

**Comment by yvaucher** [comment]
This has been merged in 8.0 thus I close this issue

https://github.com/OCA/l10n-switzerland/commit/f8eee86c32d1b89414b2d3bf5c874dc1a1a62dbc
