### ISSUE TITLE
bank.xml needs an update

### ISSUE THREAD

**Issue by omacchioni** [OCA/l10n-switzerland#84]
I guess the data is based on http://www.six-interbank-clearing.com/dam/downloads/bc-bank-master/bcbankenstamm. There has been new banks since them (some banks have been removed as well, but we need to keep them in odoo for consistency reasons).

I don't know where to find the script to generate the .xml file though.

**Comment by nbessi** [comment]
Hello, 

The file was updated in branch 8.0 of localisation.  It may be backported if needed.

Regards

Nicolas
